version: '2'

services:
  db:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_LINK: "db:5432"

volumes:
  pg_data:
    driver: local
